spring:
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #h2 설정
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enable: true